project_id = "tmsktyzdbqqmhyczkngn"

[functions.generate-story]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.export-pdf]
verify_jwt = true

[functions.create-print-order]
verify_jwt = true

[functions.process-print-payment]
verify_jwt = true

[functions.add-to-brevo]
verify_jwt = true