project_id = "tmsktyzdbqqmhyczkngn"

[functions.generate-story]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true