// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmsktyzdbqqmhyczkngn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtc2t0eXpkYnFxbWh5Y3prbmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MzA4NjcsImV4cCI6MjA2OTUwNjg2N30.Qc2szKGShcUA8fRQgPCtYRB8vFMh2UG5n25uuY8_87I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});